create table products (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  subtitle text,
  description text,
  price numeric,
  originalPrice numeric,
  stock integer,
  category text,
  status text,
  images jsonb,
  sku text,
  rating numeric,
  reviewCount integer,
  customerCount integer,
  createdAt timestamp with time zone default now(),
  updatedAt timestamp with time zone default now(),
  keyIngredients jsonb,
  benefits jsonb,
  usageSteps jsonb,
  certifications jsonb,
  pricingPlans jsonb,
  tags jsonb,
  featured boolean,
  badges jsonb
);
